### ISSUE TITLE
Expose content via API

### ISSUE THREAD

**Issue by benbalter** [isitchristmas/web#90]
I see there's `/rss.xml`, but it would be great if there were a `/api` or similar endpoint, that could return the site content (yes/no status) in machine readable format. You could theoretically get this information via the RSS feed, but a simple JSON representation, not tied to the date, would be much more natural for developers. This would enable users to create mobile apps, command-line utilities, etc.

**Comment by fowlinbasket** [comment]
I know it has been a long time since the API was implemented. However, I would like to fetch from the API using frontend JavaScript, but there has been a consistent failure to fetch because no 'Access-Control-Allow-Origin' header is present in the response. It would be appreciated if that could be implemented.
